deps src: Automatic update.

diff --git a/src/luarocks/configure b/src/luarocks/configure
--- a/src/luarocks/configure
+++ b/src/luarocks/configure
@@ -40,7 +40,7 @@ system's package manager.
                             Default is \$PREFIX
 
 --lua-version=VERSION       Use specific Lua version: 5.1, 5.2, or 5.3
-                            Default is "$LUA_VERSION"
+                            Default is auto-detected.
 --lua-suffix=SUFFIX         Versioning suffix to use in Lua filenames.
                             Default is "$LUA_SUFFIX" (lua$LUA_SUFFIX...)
 --with-lua=PREFIX           Use Lua from given prefix.
@@ -71,25 +71,10 @@ EOF
 # Helper functions
 
 find_program() {
-   path="$PATH"
-   item="`echo "$path" | sed 's/\([^:]*\):.*/\1/'`"
-   path="`echo "$path" | sed -n 's/[^:]*::*\(.*\)/\1/p'`"
-   found="no"
-   while [ -n "$item" ]
-   do
-      if [ -f "$item/$1" ]
-      then
-         found="yes"
-         break
-      fi
-      item="`echo "$path" | sed 's/\([^:]*\):.*/\1/'`"
-      path="`echo "$path" | sed -n 's/[^:]*::*\(.*\)/\1/p'`"
-   done
-   if [ "$found" = "yes" ]
+   prog=`command -v "$1" 2>/dev/null`
+   if [ -n "$prog" ]
    then
-      echo "$item"
-   else
-      echo ""
+      dirname "$prog"
    fi
 }
 
@@ -116,7 +101,7 @@ find_helper() {
       fi
       shift
    done
-   echo "Could not find a $explanation. Tried: $tried."
+   echo "Could not find $explanation. Tried: $tried."
    die "Make sure one of them is installed and available in your PATH."
 }
 
@@ -241,18 +226,20 @@ then
 fi
 
 detect_lua_version() {
-   detected_lua=`$1 -e 'print(_VERSION:sub(5))' 2> /dev/null`
-   if [ "$detected_lua" = "5.1" -o "$detected_lua" = "5.2" -o "$detected_lua" = "5.3" ]
+   detected_lua=`$1 -e 'print(_VERSION:match(" (5%.[123])$"))' 2> /dev/null`
+   if [ "$detected_lua" != "nil" ]
    then
-      echo "Lua version detected: $detected_lua"
       if [ "$LUA_VERSION_SET" != "yes" ]
       then
+         echo "Lua version detected: $detected_lua"
          LUA_VERSION=$detected_lua
-      elif [ "$LUA_VERSION" != "$detected_lua" ]
+         return 0
+      elif [ "$LUA_VERSION" = "$detected_lua" ]
       then
-         die "This clashes with the value of --lua-version. Please check your configuration."
+         return 0
       fi
    fi
+   return 1
 }
 
 search_interpreter() {
@@ -262,23 +249,35 @@ search_interpreter() {
       find_lua="$LUA_BINDIR"
    elif [ "$LUA_DIR_SET" = "yes" ]
    then
-      if [ -f "$LUA_DIR/bin/lua$suffix" ]
+      LUA_BINDIR="$LUA_DIR/bin"
+      if [ -f "$LUA_BINDIR/lua$suffix" ]
       then
-         find_lua="$LUA_DIR/bin"
+         find_lua="$LUA_BINDIR"
       fi
    else
       find_lua=`find_program lua$suffix`
    fi
    if [ -n "$find_lua" -a -x "$find_lua/lua$suffix" ]
    then
-      echo "Lua interpreter found: $find_lua/lua$suffix..."
-      LUA_SUFFIX=$suffix
-      detect_lua_version "$find_lua/lua$LUA_SUFFIX"
-      return 0
+      if detect_lua_version "$find_lua/lua$suffix"
+      then
+         echo "Lua interpreter found: $find_lua/lua$suffix..."
+         if [ "$LUA_BINDIR_SET" != "yes" ]
+         then
+            LUA_BINDIR="$find_lua"
+         fi
+         if [ "$LUA_DIR_SET" != "yes" ]
+         then
+            LUA_DIR=`dirname "$find_lua"`
+         fi
+         LUA_SUFFIX="$suffix"
+         return 0
+      fi
    fi
    return 1
 }
 
+lua_interp_found=no
 if [ "$LUA_SUFFIX_SET" != "yes" ]
 then
    if [ "$LUA_VERSION_SET" = "yes" -a "$LUA_VERSION" = "5.1" ]
@@ -293,31 +292,35 @@ then
    else
       suffixes="5.3 53 -5.3 -53 5.2 52 -5.2 -52 5.1 51 -5.1 -51"
    fi
-   lua_interp_found=no
-   for suffix in "" `echo $suffixes`
+   for suffix in `echo $suffixes` ""
    do
       search_interpreter "$suffix" && {
          lua_interp_found=yes
          break
       }
    done
+else
+   search_interpreter "$LUA_SUFFIX" && {
+      lua_interp_found=yes
+   }
 fi
 
-if [ "$LUA_DIR_SET" != "yes" ]
+if [ "$lua_interp_found" != "yes" ]
 then
-   if [ -z "$find_lua" ]
-   then
-      echo_n "Looking for Lua... "
-      find_lua=`find_program lua$LUA_SUFFIX`
-   fi
+   [ "$LUA_VERSION_SET" ] && { interp="Lua $LUA_VERSION" ;} || { interp="Lua" ;}
+   [ "$LUA_DIR_SET" -o "$LUA_BINDIR_SET" ] && { where="$LUA_BINDIR" ;} || { interp="\$PATH" ;}
+   echo "$interp interpreter not found in $where"
+   die "You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help."
+fi
 
-   if [ -n "$find_lua" ]
+if [ "$LUA_VERSION_SET" = "yes" ]
+then
+   echo_n "Checking if $LUA_BINDIR/lua$LUA_SUFFIX is Lua version $LUA_VERSION... "
+   if detect_lua_version "$LUA_BINDIR/lua$LUA_SUFFIX"
    then
-      LUA_DIR=`dirname $find_lua`
-      LUA_BINDIR="$find_lua"
-      echo "lua$LUA_SUFFIX found in \$PATH: $find_lua"
+      echo "yes"
    else
-      echo "lua$LUA_SUFFIX not found in \$PATH."
+      echo "no"
       die "You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help."
    fi
 fi
@@ -330,23 +333,6 @@ fi
 if [ "$LUA_LIBDIR_SET" != "yes" ]
 then
    LUA_LIBDIR="$LUA_DIR/lib"
-fi
-
-if [ "$LUA_DIR_SET" = "yes" -a "$LUA_BINDIR_SET" != "yes" ]
-then
-   LUA_BINDIR="$LUA_DIR/bin"
-fi
-
-if [ "$lua_interp_found" != "yes" ]
-then
-   echo_n "Checking Lua interpreter... "
-   if [ -x "$LUA_BINDIR/lua$LUA_SUFFIX" ]
-   then
-      echo "lua$LUA_SUFFIX found in $LUA_BINDIR"
-   else
-      echo "lua$LUA_SUFFIX not found (looked in $LUA_BINDIR)"
-      die "You may want to use the flag --with-lua or --with-lua-bin. See --help."
-   fi
 fi
 
 echo_n "Checking Lua includes... "
@@ -375,17 +361,31 @@ else
    fi
 fi
 
+echo_n "Checking if Lua header version matches that of the interpreter... "
+header_version=$(sed -n 's/.*LUA_VERSION_NUM.*5.\(.\).*/5.\1/p' "$lua_h")
+if [ "$header_version" = "$LUA_VERSION" ]
+then
+   echo "yes"
+else
+   echo "no"
+   echo "lua.h version mismatch (interpreter: $LUA_VERSION; lua.h: $header_version)."
+   die "You may want to use the flag --with-lua or --with-lua-include. See --help."
+fi
+
+
 if [ "$LUAROCKS_DOWNLOADER_SET" != "yes" ]
 then
-   find_helper "downloader helper program" curl wget fetch
+   find_helper "a downloader helper program" curl wget fetch
    LUAROCKS_DOWNLOADER=$HELPER
 fi
 
 if [ "$LUAROCKS_MD5CHECKER_SET" != "yes" ]
 then
-   find_helper "MD5 checksum calculator" md5sum openssl md5
+   find_helper "a MD5 checksum calculator" md5sum openssl md5
    LUAROCKS_MD5CHECKER=$HELPER
 fi
+
+find_helper "an 'unzip' program" unzip
 
 echo_n "Configuring for system... "
 if uname -s
